package config

import (
	"github.com/lnwzaaa007/Project_SA_School-system/backend/entity"
)

func seedCourses() {
	db.Model(&entity.Course{}).Create([]entity.Course{
		{
			Course_Code:    "ท21101",
			Course_Name:    "ภาษาไทย 1",
			Credit_Num:     1.0,
			Classroom:      101,
			Class_in_week:  2,
			Hours_of_term:  40,
			SubjectGroupID: 1,
			GradeID:        1,
			TermID:         1,
			TeacherID:      1,
		},
		{
			Course_Code:    "ค21101",
			Course_Name:    "คณิตศาสตร์ 1",
			Credit_Num:     1.0,
			Classroom:      101,
			Class_in_week:  2,
			Hours_of_term:  40,
			SubjectGroupID: 2,
			GradeID:        1,
			TermID:         1,
			TeacherID:      2,
		},
		{
			Course_Code:    "ว21101",
			Course_Name:    "วิทยาศาสตร์ 1",
			Credit_Num:     1.5,
			Classroom:      101,
			Class_in_week:  2,
			Hours_of_term:  60,
			SubjectGroupID: 3,
			GradeID:        1,
			TermID:         1,
			TeacherID:      3,
		},
		{
			Course_Code:    "ส21101",
			Course_Name:    "สังคมศึกษา 1",
			Credit_Num:     1.5,
			Classroom:      101,
			Class_in_week:  3,
			Hours_of_term:  60,
			SubjectGroupID: 4,
			GradeID:        1,
			TermID:         1,
			TeacherID:      4,
		},
		{
			Course_Code:    "ส21103",
			Course_Name:    "ประวัติศาสตร์ 1",
			Credit_Num:     0.5,
			Classroom:      101,
			Class_in_week:  1,
			Hours_of_term:  20,
			SubjectGroupID: 4,
			GradeID:        1,
			TermID:         1,
			TeacherID:      4,
		},
		{
			Course_Code:    "พ21101",
			Course_Name:    "สุขศึกษา 1",
			Credit_Num:     0.5,
			Classroom:      101,
			Class_in_week:  1,
			Hours_of_term:  20,
			SubjectGroupID: 5,
			GradeID:        1,
			TermID:         1,
			TeacherID:      5,
		},
		{
			Course_Code:    "พ21103",
			Course_Name:    "พลศึกษา 1",
			Credit_Num:     0.5,
			Classroom:      101,
			Class_in_week:  1,
			Hours_of_term:  20,
			SubjectGroupID: 5,
			GradeID:        1,
			TermID:         1,
			TeacherID:      5,
		},
		{
			Course_Code:    "ศ21101",
			Course_Name:    "ดนตรี 1",
			Credit_Num:     0.5,
			Classroom:      101,
			Class_in_week:  1,
			Hours_of_term:  20,
			SubjectGroupID: 6,
			GradeID:        1,
			TermID:         1,
			TeacherID:      6,
		},
		{
			Course_Code:    "ศ21103",
			Course_Name:    "นาฏศิลป์ 1",
			Credit_Num:     0.5,
			Classroom:      101,
			Class_in_week:  1,
			Hours_of_term:  20,
			SubjectGroupID: 6,
			GradeID:        1,
			TermID:         1,
			TeacherID:      6,
		},
		{
			Course_Code:    "ง21101",
			Course_Name:    "การงานอาชีพ 1 (ธุรกิจ)",
			Credit_Num:     0.5,
			Classroom:      101,
			Class_in_week:  1,
			Hours_of_term:  20,
			SubjectGroupID: 7,
			GradeID:        1,
			TermID:         1,
			TeacherID:      7,
		},
		{
			Course_Code:    "อ21101",
			Course_Name:    "ภาษาอังกฤษ 1",
			Credit_Num:     1.5,
			Classroom:      101,
			Class_in_week:  3,
			Hours_of_term:  60,
			SubjectGroupID: 8,
			GradeID:        1,
			TermID:         1,
			TeacherID:      8,
		},
		{
			Course_Code:    "ค21201",
			Course_Name:    "คณิตศาสตร์เพิ่มเติม 1",
			Credit_Num:     1.0,
			Classroom:      101,
			Class_in_week:  2,
			Hours_of_term:  40,
			SubjectGroupID: 2,
			GradeID:        1,
			TermID:         1,
			TeacherID:      2,
		},
		{
			Course_Code:    "ว21281",
			Course_Name:    "วิทยาศาสตร์คำนวณ 1",
			Credit_Num:     1.0,
			Classroom:      101,
			Class_in_week:  2,
			Hours_of_term:  40,
			SubjectGroupID: 3,
			GradeID:        1,
			TermID:         1,
			TeacherID:      3,
		},
		{
			Course_Code:    "อ21201",
			Course_Name:    "ภาษาอังกฤษสร้างสรรค์ 1",
			Credit_Num:     0.5,
			Classroom:      101,
			Class_in_week:  1,
			Hours_of_term:  20,
			SubjectGroupID: 8,
			GradeID:        1,
			TermID:         1,
			TeacherID:      8,
		},{
			Course_Code:    "อ21221",
			Course_Name:    "ทักษะการใช้ภาษาอังกฤษ 1",
			Credit_Num:     1.0,
			Classroom:      101,
			Class_in_week:  2,
			Hours_of_term:  40,
			SubjectGroupID: 8,
			GradeID:        1,
			TermID:         1,
			TeacherID:      8,
		},
		{
			Course_Code:    "ว21283",
			Course_Name:    "ชีววิทยาAP ",
			Credit_Num:     1.0,
			Classroom:      101,
			Class_in_week:  2,
			Hours_of_term:  40,
			SubjectGroupID: 3,
			GradeID:        1,
			TermID:         1,
			TeacherID:      3,
		},

	})
}

func seedSubjectGroup() {
	db.Model(&entity.Subject_Group{}).Create([]entity.Subject_Group{
		{SubjectGroup_Name: "กลุ่มสาระการเรียนรู้ภาษาไทย"},
		{SubjectGroup_Name: "กลุ่มสาระการเรียนรู้คณิตศาสตร์"},
		{SubjectGroup_Name: "กลุ่มสาระการเรียนรู้วิทยาศาสตร์และเทคโนโลยี"},
		{SubjectGroup_Name: "กลุ่มสาระการเรียนรู้สังคมศึกษา ศาสนา และวัฒนธรรม"},
		{SubjectGroup_Name: "กลุ่มสาระการเรียนรู้สุขศึกษาและพลศึกษา"},
		{SubjectGroup_Name: "กลุ่มสาระการเรียนรู้ศิลปะ"},
		{SubjectGroup_Name: "กลุ่มสาระการเรียนรู้การงานอาชีพ"},
		{SubjectGroup_Name: "กลุ่มสาระการเรียนรู้ภาษาต่างประเทศ"},
	})
}