package config
import (
	"github.com/lnwzaaa007/Project_SA_School-system/backend/entity"
	
)
func seeddistrict(){
	db.Model(&entity.District{}).Create([]entity.District{
		{ProvinceID: 1, District_name: "เขตพระนคร",},
		{ProvinceID: 1, District_name: "เขตดุสิต",},
		{ProvinceID: 1, District_name: "เขตหนองจอก",},
		{ProvinceID: 1, District_name: "เขตบางรัก",},
		{ProvinceID: 1, District_name: "เขตบางเขน",},
		{ProvinceID: 1, District_name: "เขตบางกะปิ",},
		{ProvinceID: 1, District_name: "เขตปทุมวัน",},
		{ProvinceID: 1, District_name: "เขตป้อมปราบศัตรูพ่าย",},
		{ProvinceID: 1, District_name: "เขตพระโขน",},
		{ProvinceID: 1, District_name: "เขตมีนบุรี",},
		{ProvinceID: 1, District_name: "เขตลาดกระบัง",},
		{ProvinceID: 1, District_name: "เขตยานนาวา",},
		{ProvinceID: 1, District_name: "เขตสัมพันธวงศ์",},
		{ProvinceID: 1, District_name: "เขตพญาไท",},
		{ProvinceID: 1, District_name: "เขตธนบุรี",},
		{ProvinceID: 1, District_name: "เขตบางกอกใหญ่",},
		{ProvinceID: 1, District_name: "เขตห้วยขวาง",},
		{ProvinceID: 1, District_name: "เขตคลองสาน",},
		{ProvinceID: 1, District_name: "เขตตลิ่งชัน",},
		{ProvinceID: 1, District_name: "เขตบางกอกน้อย",},
		{ProvinceID: 1, District_name: "เขตบางขุนเทียน",},
		{ProvinceID: 1, District_name: "เขตภาษีเจริญ",},
		{ProvinceID: 1, District_name: "เขตหนองแขม",},
		{ProvinceID: 1, District_name: "เขตราษฎร์บูรณะ",},
		{ProvinceID: 1, District_name: "เขตบางพลัด",},
		{ProvinceID: 1, District_name: "เขตดินแดง",},
		{ProvinceID: 1, District_name: "เขตบึงกุ่ม",},
		{ProvinceID: 1, District_name: "เขตสาทร",},
		{ProvinceID: 1, District_name: "เขตบางซื่อ",},
		{ProvinceID: 1, District_name: "เขตจตุจักร",},
		{ProvinceID: 1, District_name: "เขตบางคอแหลม",},
		{ProvinceID: 1, District_name: "เขตประเวศ",},
		{ProvinceID: 1, District_name: "เขตคลองเตย",},
		{ProvinceID: 1, District_name: "เขตสวนหลวง",},
		{ProvinceID: 1, District_name: "เขตจอมทอง",},
		{ProvinceID: 1, District_name: "เขตดอนเมือง",},
		{ProvinceID: 1, District_name: "เขตราชเทวี",},
		{ProvinceID: 1, District_name: "เขตลาดพร้าว",},
		{ProvinceID: 1, District_name: "เขตวัฒนา",},
		{ProvinceID: 1, District_name: "เขตบางแค",},
		{ProvinceID: 1, District_name: "เขตหลักสี่",},
		{ProvinceID: 1, District_name: "เขตสายไหม",},
		{ProvinceID: 1, District_name: "เขตคันนายาว",},
		{ProvinceID: 1, District_name: "เขตสะพานสูง",},
		{ProvinceID: 1, District_name: "เขตวังทองหลาง",},
		{ProvinceID: 1, District_name: "เขตคลองสามวา",},
		{ProvinceID: 1, District_name: "เขตบางนา",},
		{ProvinceID: 1, District_name: "เขตทวีวัฒนา",},
		{ProvinceID: 1, District_name: "เขตทุ่งครุ",},
		{ProvinceID: 1, District_name: "เขตบางบอน",},
		
		{ProvinceID: 2, District_name: "เมืองกระบี่",},
		{ProvinceID: 2, District_name: "เขาพนม",},
		{ProvinceID: 2, District_name: "เกาะลันตา",},
		{ProvinceID: 2, District_name: "คลองท่อม",},
		{ProvinceID: 2, District_name: "อ่าวลึก",},
		{ProvinceID: 2, District_name: "ปลายพระยา"},
		{ProvinceID: 2, District_name: "ลำทับ",},
		{ProvinceID: 2, District_name: "เหนือคลอง",},

		{ProvinceID: 3, District_name: "เมืองกาญจนบุรี",},
		{ProvinceID: 3, District_name: "ไทรโยค",},
		{ProvinceID: 3, District_name: "บ่อพลอย",},
		{ProvinceID: 3, District_name: "ศรีสวัสดิ์",},
		{ProvinceID: 3, District_name: "ท่ามะกา",},
		{ProvinceID: 3, District_name: "ท่าม่วง",},
		{ProvinceID: 3, District_name: "ทองผาภูมิ",},
		{ProvinceID: 3, District_name: "สังขละบุรี",},
		{ProvinceID: 3, District_name: "พนมทวน",},
		{ProvinceID: 3, District_name: "เลาขวัญ",},
		{ProvinceID: 3, District_name: "ด่านมะขามเตี้ย",},
		{ProvinceID: 3, District_name: "หนองปรือ",},
		{ProvinceID: 3, District_name: "ห้วยกระเจา",},

		{ProvinceID: 4, District_name: "เมืองกาฬสินธุ์",},
		{ProvinceID: 4, District_name: "กมลาไสย",},
		{ProvinceID: 4, District_name: "กุฉินารายณ์",},
		{ProvinceID: 4, District_name: "เขาวง",},
		{ProvinceID: 4, District_name: "คำม่วง",},
		{ProvinceID: 4, District_name: "ฆ้องชัย",},
		{ProvinceID: 4, District_name: "ดอนจาน",},
		{ProvinceID: 4, District_name: "ท่าคันโท",},
		{ProvinceID: 4, District_name: "นาคู",},
		{ProvinceID: 4, District_name: "นามน",},
		{ProvinceID: 4, District_name: "ยางตลาด",},
		{ProvinceID: 4, District_name: "ร่องคำ",},
		{ProvinceID: 4, District_name: "สมเด็จ",},
		{ProvinceID: 4, District_name: "สหัสขันธ์",},
		{ProvinceID: 4, District_name: "หนองกุงศรี",},
		{ProvinceID: 4, District_name: "ห้วยผึ้ง",},
		{ProvinceID: 4, District_name: "ห้วยเม็ก",},
		
		{ProvinceID: 5, District_name: "เมืองกำแพงเพชร",},
		{ProvinceID: 5, District_name: "โกสัมพีนคร",},
		{ProvinceID: 5, District_name: "ขาณุวรลักษบุรี",},
		{ProvinceID: 5, District_name: "คลองขลุง",},
		{ProvinceID: 5, District_name: "คลองลาน",},
		{ProvinceID: 5, District_name: "ทรายทองวัฒนา",},
		{ProvinceID: 5, District_name: "ไทรงาม",},
		{ProvinceID: 5, District_name: "บึงสามัคคี",},
		{ProvinceID: 5, District_name: "ปางศิลาทอง",},
		{ProvinceID: 5, District_name: "พรานกระต่าย",},
		{ProvinceID: 5, District_name: "ลานกระบือ",},

		{ProvinceID: 6, District_name: "เมืองขอนแก่น",},
		{ProvinceID: 6, District_name: "อุบลรัตน์",},
		{ProvinceID: 6, District_name: "หนองสองห้อง",},
		{ProvinceID: 6, District_name: "หนองเรือ",},
		{ProvinceID: 6, District_name: "หนองนาคำ",},
		{ProvinceID: 6, District_name: "สีชมพู",},
		{ProvinceID: 6, District_name: "แวงใหญ่",},
		{ProvinceID: 6, District_name: "แวงน้อย",},
		{ProvinceID: 6, District_name: "เวียงเก่า",},
		{ProvinceID: 6, District_name: "มัญจาคีรี",},
		{ProvinceID: 6, District_name: "ภูเวียง",},
		{ProvinceID: 6, District_name: "ภูผาม่าน",},
		{ProvinceID: 6, District_name: "พล",},
		{ProvinceID: 6, District_name: "พระยืน",},
		{ProvinceID: 6, District_name: "เปือยน้อย",},
		{ProvinceID: 6, District_name: "บ้านแฮด",},
		{ProvinceID: 6, District_name: "บ้านฝาง",},
		{ProvinceID: 6, District_name: "บ้านไผ่",},
		{ProvinceID: 6, District_name: "โนนศิลา",},
		{ProvinceID: 6, District_name: "น้ำพอง",},
		{ProvinceID: 6, District_name: "ซำสูง",},
		{ProvinceID: 6, District_name: "ชุมแพ",},
		{ProvinceID: 6, District_name: "ชนบท",},
		{ProvinceID: 6, District_name: "โคกโพธิ์ไชย",},
		{ProvinceID: 6, District_name: "เขาสวนกวาง",},
		{ProvinceID: 6, District_name: "กระนวน",},
		
		{ProvinceID: 7, District_name: "เมืองจันทบุรี",},
		{ProvinceID: 7, District_name: "แก่งหางแมว",},
		{ProvinceID: 7, District_name: "ขลุง",},
		{ProvinceID: 7, District_name: "เขาคิชฌกูฏ",},
		{ProvinceID: 7, District_name: "ท่าใหม่",},
		{ProvinceID: 7, District_name: "นายายอาม",},
		{ProvinceID: 7, District_name: "โป่งน้ำร้อน"},
		{ProvinceID: 7, District_name: "มะขาม",},
		{ProvinceID: 7, District_name: "สอยดาว",},
		{ProvinceID: 7, District_name: "แหลมสิงห์",},
		
		{ProvinceID: 8, District_name: "เมืองฉะเชิงเทรา",},
		{ProvinceID: 8, District_name: "สนามชัยเขต",},
		{ProvinceID: 8, District_name: "ราชสาส์น",},
		{ProvinceID: 8, District_name: "พนมสารคาม",},
		{ProvinceID: 8, District_name: "แปลงยาว",},
		{ProvinceID: 8, District_name: "บ้านโพธิ์",},
		{ProvinceID: 8, District_name: "บางปะกง",},
		{ProvinceID: 8, District_name: "บางน้ำเปรี้ยว",},
		{ProvinceID: 8, District_name: "บางคล้า",},
		{ProvinceID: 8, District_name: "ท่าตะเกียบ",},
		{ProvinceID: 8, District_name: "คลองเขื่อน",},

		{ProvinceID: 9, District_name: "เมืองชลบุรี",},
		{ProvinceID: 9, District_name: "เกาะจันทร์",},
		{ProvinceID: 9, District_name: "เกาะสีชัง",},
		{ProvinceID: 9, District_name: "บ่อทอง",},
		{ProvinceID: 9, District_name: "บางละมุง",},
		{ProvinceID: 9, District_name: "บ้านบึง",},
		{ProvinceID: 9, District_name: "พนัสนิคม",},
		{ProvinceID: 9, District_name: "พานทอง",},
		{ProvinceID: 9, District_name: "ศรีราชา",},
		{ProvinceID: 9, District_name: "สัตหีบ",},
		{ProvinceID: 9, District_name: "หนองใหญ่",},

		{ProvinceID: 10, District_name: "เมืองชัยนาท",},
		{ProvinceID: 10, District_name: "เนินขาม",},
		{ProvinceID: 10, District_name: "โนรมย์",},
		{ProvinceID: 10, District_name: "วัดสิงห์",},
		{ProvinceID: 10, District_name: "สรรคบุรี",},
		{ProvinceID: 10, District_name: "สรรพยา",},
		{ProvinceID: 10, District_name: "หนองมะโมง",},
		{ProvinceID: 10, District_name: "หันคา",},

		{ProvinceID: 11, District_name: "เมืองชัยภูมิ",},
		{ProvinceID: 11, District_name: "ภูเขียว",},
		{ProvinceID: 11, District_name: "ภักดีชุมพล",},
		{ProvinceID: 11, District_name: "บำเหน็จณรงค์",},
		{ProvinceID: 11, District_name: "บ้านแท่น",},
		{ProvinceID: 11, District_name: "บ้านเขว้า",},
		{ProvinceID: 11, District_name: "เนินสง่า",},
		{ProvinceID: 11, District_name: "เทพสถิต",},
		{ProvinceID: 11, District_name: "ซับใหญ่",},
		{ProvinceID: 11, District_name: "จัตุรัส",},
		{ProvinceID: 11, District_name: "คอนสาร",},
		{ProvinceID: 11, District_name: "หนองบัวระเหว",},
		{ProvinceID: 11, District_name: "หนองบัวแดง",},
		{ProvinceID: 11, District_name: "แก้งคร้อ",},
		{ProvinceID: 11, District_name: "เกษตรสมบูรณ์",},

		{ProvinceID: 12, District_name: "เมืองชุมพร",},
		{ProvinceID: 12, District_name: "ท่าแซะ",},
		{ProvinceID: 12, District_name: "ปะทิว",},
		{ProvinceID: 12, District_name: "ละแม",},
		{ProvinceID: 12, District_name: "หลังสวน",},
		{ProvinceID: 12, District_name: "พะโต๊ะ",},
		{ProvinceID: 12, District_name: "สวี",},
		{ProvinceID: 12, District_name: "ทุ่งตะโก",},

		{ProvinceID: 13, District_name: "เมืองเชียงใหม่",},
		{ProvinceID: 13, District_name: "กัลยาณิวัฒนา",},
		{ProvinceID: 13, District_name: "จอมทอง",},
		{ProvinceID: 13, District_name: "เชียงดาว",},
		{ProvinceID: 13, District_name: "ไชยปราการ",},
		{ProvinceID: 13, District_name: "ดอยเต่า",},
		{ProvinceID: 13, District_name: "ดอยสะเก็ด",},
		{ProvinceID: 13, District_name: "ดอยหล่อ",},
		{ProvinceID: 13, District_name: "ฝาง",},
		{ProvinceID: 13, District_name: "พร้าว",},
		{ProvinceID: 13, District_name: "แม่แจ่ม",},
		{ProvinceID: 13, District_name: "แม่แตง",},
		{ProvinceID: 13, District_name: "แม่ริม",},
		{ProvinceID: 13, District_name: "แม่วาง",},
		{ProvinceID: 13, District_name: "แม่ออน",},
		{ProvinceID: 13, District_name: "แม่อาย",},
		{ProvinceID: 13, District_name: "เวียงแหง",},
		{ProvinceID: 13, District_name: "สะเมิง",},
		{ProvinceID: 13, District_name: "สันกำแพง",},
		{ProvinceID: 13, District_name: "สันทราย",},
		{ProvinceID: 13, District_name: "สันป่าตอง",},
		{ProvinceID: 13, District_name: "สารภี",},
		{ProvinceID: 13, District_name: "หางดง",},
		{ProvinceID: 13, District_name: "ออมก๋อย",},
		{ProvinceID: 13, District_name: "ฮอด",},

		{ProvinceID: 14, District_name: "เมืองเชียงราย",},
		{ProvinceID: 14, District_name: "ขุนตาล",},
		{ProvinceID: 14, District_name: "เชียงของ",},
		{ProvinceID: 14, District_name: "เชียงแสน",},
		{ProvinceID: 14, District_name: "ดอยหลวง",},
		{ProvinceID: 14, District_name: "เทิง",},
		{ProvinceID: 14, District_name: "ป่าแดด",},
		{ProvinceID: 14, District_name: "พญาเม็งราย",},
		{ProvinceID: 14, District_name: "พาน",},
		{ProvinceID: 14, District_name: "แม่จัน",},
		{ProvinceID: 14, District_name: "แม่ฟ้าหลวง",},
		{ProvinceID: 14, District_name: "แม่ลาว",},
		{ProvinceID: 14, District_name: "แม่สรวย",},
		{ProvinceID: 14, District_name: "เวียงแก่น",},
		{ProvinceID: 14, District_name: "เวียงชัย",},
		{ProvinceID: 14, District_name: "เวียงเชียงรุ้ง",},
		{ProvinceID: 14, District_name: "เวียงป่าเป้า",},

		{ProvinceID: 15, District_name: "เมืองตรัง",},
		{ProvinceID: 15, District_name: "กันตัง",},
		{ProvinceID: 15, District_name: "นาโยง",},
		{ProvinceID: 15, District_name: "ปะเหลียน",},
		{ProvinceID: 15, District_name: "ย่านตาขาว",},
		{ProvinceID: 15, District_name: "รังสิตา",},
		{ProvinceID: 15, District_name: "วังวิเศษ",},
		{ProvinceID: 15, District_name: "สิเกา",},
		{ProvinceID: 15, District_name: "ห้วยยอด",},
		{ProvinceID: 15, District_name: "หาดสำราญ",},

		{ProvinceID: 16, District_name: "เมืองตราด",},
		{ProvinceID: 16, District_name: "เกาะกูด",},
		{ProvinceID: 16, District_name: "เกาะช้าง",},
		{ProvinceID: 16, District_name: "เขาสมิง",},
		{ProvinceID: 16, District_name: "คลองใหญ่",},
		{ProvinceID: 16, District_name: "บ่อไร่",},
		{ProvinceID: 16, District_name: "แหลมงอบ",},

		{ProvinceID: 17, District_name: "เมืองตาก",},
		{ProvinceID: 17, District_name: "อุ้มผาง",},
		{ProvinceID: 17, District_name: "สามเงา",},
		{ProvinceID: 17, District_name: "วังเจ้า",},
		{ProvinceID: 17, District_name: "แม่สอด",},
		{ProvinceID: 17, District_name: "แม่ระมาด",},
		{ProvinceID: 17, District_name: "พบพระ",},
		{ProvinceID: 17, District_name: "บ้านตาก",},
		{ProvinceID: 17, District_name: "ท่าสองยาง",},

		{ProvinceID: 18, District_name: "เมืองนครนายก",},
		{ProvinceID: 18, District_name: "บ้านนา",},
		{ProvinceID: 18, District_name: "ปากพลี",},
		{ProvinceID: 18, District_name: "องครักษ์",},

		{ProvinceID: 19, District_name: "เมืองนครปฐม",},
		{ProvinceID: 19, District_name: "กำแพงแสน",},
		{ProvinceID: 19, District_name: "ดอนตูม",},
		{ProvinceID: 19, District_name: "นครชัยศรี",},
		{ProvinceID: 19, District_name: "บางเลน",},
		{ProvinceID: 19, District_name: "พุทธมณฑล",},
		{ProvinceID: 19, District_name: "สามพราน",},

		{ProvinceID: 20, District_name: "เมืองนครพนม",},
		{ProvinceID: 20, District_name: "ท่าอุเทน",},
		{ProvinceID: 20, District_name: "ธาตุพนม",},
		{ProvinceID: 20, District_name: "นาแก",},
		{ProvinceID: 20, District_name: "นาทม",},
		{ProvinceID: 20, District_name: "นาหว้า",},
		{ProvinceID: 20, District_name: "บ้านแพง",},
		{ProvinceID: 20, District_name: "ปลาปาก",},
		{ProvinceID: 20, District_name: "เรณูนคร",},
		{ProvinceID: 20, District_name: "วังยาง",},
		{ProvinceID: 20, District_name: "ศรีสงคราม",},
		
		{ProvinceID: 21, District_name: "เมืองนครราชสีมา",},
		{ProvinceID: 21, District_name: "แก้งสนามนาง",},
		{ProvinceID: 21, District_name: "ขามทะเลสอ",},
		{ProvinceID: 21, District_name: "ขามสะแกแสง",},
		{ProvinceID: 21, District_name: "คง",},
		{ProvinceID: 21, District_name: "ครบุรี",},
		{ProvinceID: 21, District_name: "จักราช",},
		{ProvinceID: 21, District_name: "เฉลิมพระเกียรติ",},
		{ProvinceID: 21, District_name: "ชุมพวง",},
		{ProvinceID: 21, District_name: "โชคชัย",},
		{ProvinceID: 21, District_name: "ด่านขุนทด",},
		{ProvinceID: 21, District_name: "เทพารักษ์",},
		{ProvinceID: 21, District_name: "โนนแดง",},
		{ProvinceID: 21, District_name: "โนนไทย",},
		{ProvinceID: 21, District_name: "โนนสูง",},
		{ProvinceID: 21, District_name: "บัวลาย",},
		{ProvinceID: 21, District_name: "บัวใหญ่",},
		{ProvinceID: 21, District_name: "บ้านเหลื่อม",},
		{ProvinceID: 21, District_name: "ประทาย",},
		{ProvinceID: 21, District_name: "ปักธงชัย",},
		{ProvinceID: 21, District_name: "ปากช่อง",},
		{ProvinceID: 21, District_name: "พระทองคำ",},
		{ProvinceID: 21, District_name: "พิมาย",},
		{ProvinceID: 21, District_name: "เมืองยาง",},
		{ProvinceID: 21, District_name: "ลำทะเมนชัย",},
		{ProvinceID: 21, District_name: "วังน้ำเขียว",},
		{ProvinceID: 21, District_name: "สีคิ้ว",},
		{ProvinceID: 21, District_name: "สีดา",},
		{ProvinceID: 21, District_name: "สูงเนิน",},
		{ProvinceID: 21, District_name: "เสิงสาง",},
		{ProvinceID: 21, District_name: "หนองบุญมาก",},
		{ProvinceID: 21, District_name: "ห้วยแถลง",},	

		{ProvinceID: 22, District_name: "เมืองนครศรีธรรมราช",},	
		{ProvinceID: 22, District_name: "ขนอม",},
		{ProvinceID: 22, District_name: "จุฬาภรณ์",},
		{ProvinceID: 22, District_name: "ฉวาง",},
		{ProvinceID: 22, District_name: "เฉลิมพระเกียรติ",},
		{ProvinceID: 22, District_name: "ชะอวด",},
		{ProvinceID: 22, District_name: "ช้างกลาง",},
		{ProvinceID: 22, District_name: "เชียรใหญ่",},
		{ProvinceID: 22, District_name: "ถ้ำพรรณรา",},
		{ProvinceID: 22, District_name: "ท่าศาลา",},
		{ProvinceID: 22, District_name: "ทุ่งสง",},
		{ProvinceID: 22, District_name: "ทุ่งใหญ่",},
		{ProvinceID: 22, District_name: "นบพิตำ",},
		{ProvinceID: 22, District_name: "นาบอน",},
		{ProvinceID: 22, District_name: "บางขัน",},
		{ProvinceID: 22, District_name: "ปากพนัง",},
		{ProvinceID: 22, District_name: "พรหมคีรี",},
		{ProvinceID: 22, District_name: "พระพรหม",},
		{ProvinceID: 22, District_name: "พิปูน",},
		{ProvinceID: 22, District_name: "ร่อนพิบูลย์",},
		{ProvinceID: 22, District_name: "ลานสกา",},
		{ProvinceID: 22, District_name: "สิชล",},
		{ProvinceID: 22, District_name: "หัวไทร",},

		{ProvinceID: 23, District_name: "เมืองนครสวรรค์",},
		{ProvinceID: 23, District_name: "หนองบัว",},
		{ProvinceID: 23, District_name: "ลาดยาว",},
		{ProvinceID: 23, District_name: "แม่วงก์",},
		{ProvinceID: 23, District_name: "แม่เปิง",},
		{ProvinceID: 23, District_name: "ไพศาลี",},
		{ProvinceID: 23, District_name: "พยุหะคีรี",},
		{ProvinceID: 23, District_name: "บรรพตพิสัย",},
		{ProvinceID: 23, District_name: "ท่าตะโก",},
		{ProvinceID: 23, District_name: "ตาคลี",},
		{ProvinceID: 23, District_name: "ตากฟ้า",},
		{ProvinceID: 23, District_name: "ชุมแสง",},
		{ProvinceID: 23, District_name: "ชุมตาบง",},
		{ProvinceID: 23, District_name: "โกรกพระ",},
		{ProvinceID: 23, District_name: "เก้าเลี้ยว",},

		{ProvinceID: 24, District_name: "เมืองนนทบุรี",},
		{ProvinceID: 24, District_name: "ไทรน้อย",},
		{ProvinceID: 24, District_name: "บางกรวย",},
		{ProvinceID: 24, District_name: "บางบัวทอง",},
		{ProvinceID: 24, District_name: "ปากเกร็ด",},
		{ProvinceID: 24, District_name: "บางใหญ่",},

		{ProvinceID: 25, District_name: "เมืองนราธิวาส",},
		{ProvinceID: 25, District_name: "สุไหงปาดี",},
		{ProvinceID: 25, District_name: "สุไหงโก-ลก",},
		{ProvinceID: 25, District_name: "สุคิริน",},
		{ProvinceID: 25, District_name: "ศรีสาคร",},
		{ProvinceID: 25, District_name: "ตากใบ",},
		{ProvinceID: 25, District_name: "รือเสาะ",},
		{ProvinceID: 25, District_name: "ระแงะ",},
		{ProvinceID: 25, District_name: "ยี่งอ",},
		{ProvinceID: 25, District_name: "บาเจาะ",},
		{ProvinceID: 25, District_name: "ตากใบ",},
		{ProvinceID: 25, District_name: "เจาะไอร้อง",},
		{ProvinceID: 25, District_name: "จะแนะ",},

		{ProvinceID: 26, District_name: "เมืองน่าน",},
		{ProvinceID: 26, District_name: "เฉลิมพระเกียรติ",},
		{ProvinceID: 26, District_name: "เชียงกลาง",},
		{ProvinceID: 26, District_name: "ท่าวังผา",},
		{ProvinceID: 26, District_name: "ทุ่งช้าง",},
		{ProvinceID: 26, District_name: "นาน้อย",},
		{ProvinceID: 26, District_name: "นาหมื่น",},
		{ProvinceID: 26, District_name: "บ่อเกลือ",},
		{ProvinceID: 26, District_name: "บ้านหลวง",},
		{ProvinceID: 26, District_name: "ปัว",},
		{ProvinceID: 26, District_name: "ภูเพียง",},
		{ProvinceID: 26, District_name: "แม่จริม",},
		{ProvinceID: 26, District_name: "เวียงสา",},
		{ProvinceID: 26, District_name: "สองแคว",},
		{ProvinceID: 26, District_name: "สันติสุข",},

		{ProvinceID: 27, District_name: "เมืองบึงกาฬ",},
		{ProvinceID: 27, District_name: "เซกา",},
		{ProvinceID: 27, District_name: "โซ่พิสัย",},
		{ProvinceID: 27, District_name: "บึงโขงหลง",},
		{ProvinceID: 27, District_name: "บุ้งคล้า",},
		{ProvinceID: 27, District_name: "ปากคาด",},
		{ProvinceID: 27, District_name: "พรเจริญ",},
		{ProvinceID: 27, District_name: "ศรีวิไล",},

		{ProvinceID: 28, District_name: "เมืองบุรีรัมย์",},
		{ProvinceID: 28, District_name: "ห้วยราช",},
		{ProvinceID: 28, District_name: "หนองหงส์",},
		{ProvinceID: 28, District_name: "หนองกี่",},
		{ProvinceID: 28, District_name: "สตึก",},
		{ProvinceID: 28, District_name: "ลำปลายมาศ",},
		{ProvinceID: 28, District_name: "ละหานทราย",},
		{ProvinceID: 28, District_name: "พุทไธสง",},
		{ProvinceID: 28, District_name: "พลับพลาชัย",},
		{ProvinceID: 28, District_name: "ปะคำ",},
		{ProvinceID: 28, District_name: "ประโคนชัย",},
		{ProvinceID: 28, District_name: "บ้านใหม่ไชยพจน์",},
		{ProvinceID: 28, District_name: "บ้านด่าน",},
		{ProvinceID: 28, District_name: "บ้านกรวด",},
		{ProvinceID: 28, District_name: "โนนสุวรรณ",},
		{ProvinceID: 28, District_name: "โนนดินแดง",},
		{ProvinceID: 28, District_name: "นาโพธิ์",},
		{ProvinceID: 28, District_name: "นางรอง",},
		{ProvinceID: 28, District_name: "ชำนิ",},
		{ProvinceID: 28, District_name: "เฉลิมพระเกียรติ",},
		{ProvinceID: 28, District_name: "แคนดง",},
		{ProvinceID: 28, District_name: "คูเมือง",},
		{ProvinceID: 28, District_name: "กระสัง",},

		{ProvinceID: 29, District_name: "เมืองปทุมธานี",},
		{ProvinceID: 29, District_name: "คลองหลวง",},
		{ProvinceID: 29, District_name: "ธัญบุรี",},
		{ProvinceID: 29, District_name: "หนองเสือ",},
		{ProvinceID: 29, District_name: "ลาดหลุมแก้ว",},
		{ProvinceID: 29, District_name: "ลำลูกกา",},
		{ProvinceID: 29, District_name: "สามโคก",},

		{ProvinceID: 30, District_name: "เมืองประจวบคีรีขันธ์",},
		{ProvinceID: 30, District_name: "หัวหิน",},
		{ProvinceID: 30, District_name: "สามร้อยยอด",},
		{ProvinceID: 30, District_name: "ปราณบุรี",},
		{ProvinceID: 30, District_name: "บางสะพาน",},
		{ProvinceID: 30, District_name: "บางสะพานน้อย",},
		{ProvinceID: 30, District_name: "ทับสะแก",},
		{ProvinceID: 30, District_name: "กุยบุรี",},

		{ProvinceID: 31, District_name: "เมืองปราจีนบุรี",},
		{ProvinceID: 31, District_name: "กบินทร์บุรี",},
		{ProvinceID: 31, District_name: "นาดี",},
		{ProvinceID: 31, District_name: "บ้านสร้าง",},
		{ProvinceID: 31, District_name: "ประจันตคาม",},
		{ProvinceID: 31, District_name: "ศรีมหาโพธิ",},
		{ProvinceID: 31, District_name: "ศรีมโหสถ",},
		
		{ProvinceID: 32, District_name: "เมืองปัตตานี",},
		{ProvinceID: 32, District_name: "โคกโพธิ์",},
		{ProvinceID: 32, District_name: "หนองจิก",},
		{ProvinceID: 32, District_name: "ปะนาเระ",},
		{ProvinceID: 32, District_name: "มายอ",},
		{ProvinceID: 32, District_name: "ทุงยางแดง",},
		{ProvinceID: 32, District_name: "สายบุรี",},
		{ProvinceID: 32, District_name: "ไม้แก่น",},
		{ProvinceID: 32, District_name: "ยะหริ่ง",},
		{ProvinceID: 32, District_name: "ยะรัง",},
		{ProvinceID: 32, District_name: "กะพ้อ",},
		{ProvinceID: 32, District_name: "แม่ลาน",},

		{ProvinceID: 33, District_name: "เมืองพะเยา",},
		{ProvinceID: 33, District_name: "จุน",},
		{ProvinceID: 33, District_name: "เชียงคำ",},
		{ProvinceID: 33, District_name: "เชียงม่วน",},
		{ProvinceID: 33, District_name: "ดอกคำใต้",},
		{ProvinceID: 33, District_name: "ปง",},
		{ProvinceID: 33, District_name: "แม่ใจ",},
		{ProvinceID: 33, District_name: "ภูซาง",},
		{ProvinceID: 33, District_name: "ภูกามยาว",},

		{ProvinceID: 34, District_name: "เมืองพระนครศรีอยุธยา",},
		{ProvinceID: 34, District_name: "ท่าเรือ",},
		{ProvinceID: 34, District_name: "นครหลวง",},
		{ProvinceID: 34, District_name: "บางไทร",},
		{ProvinceID: 34, District_name: "บางบาล",},
		{ProvinceID: 34, District_name: "บางปะอิน",},
		{ProvinceID: 34, District_name: "บางปะหัน",},
		{ProvinceID: 34, District_name: "ผักไห่",},
		{ProvinceID: 34, District_name: "ภาชี",},
		{ProvinceID: 34, District_name: "ลาดบัวหลวง",},
		{ProvinceID: 34, District_name: "วังน้อย",},
		{ProvinceID: 34, District_name: "เสนา",},
		{ProvinceID: 34, District_name: "บางซ้าย",},
		{ProvinceID: 34, District_name: "อุทัย",},
		{ProvinceID: 34, District_name: "มหาราช",},
		{ProvinceID: 34, District_name: "บ้านแพรก",},

		{ProvinceID: 35, District_name: "เมืองพังงา",},
		{ProvinceID: 35, District_name: "เกาะยาว",},
		{ProvinceID: 35, District_name: "กะปง",},
		{ProvinceID: 35, District_name: "ตะกั่วทุ่ง",},
		{ProvinceID: 35, District_name: "ตะกั่วป่า",},
		{ProvinceID: 35, District_name: "คุระบุรี",},
		{ProvinceID: 35, District_name: "ทับปุด",},
		{ProvinceID: 35, District_name: "ท้ายเหมือง",},

		{ProvinceID: 36, District_name: "เมืองพัทลุง",},
		{ProvinceID: 36, District_name: "กงหรา",},
		{ProvinceID: 36, District_name: "เขาชัยสน",},
		{ProvinceID: 36, District_name: "ตะโหมด",},
		{ProvinceID: 36, District_name: "ควนขนุน",},
		{ProvinceID: 36, District_name: "ปากพะยูน",},
		{ProvinceID: 36, District_name: "ศรีบรรพต",},
		{ProvinceID: 36, District_name: "ป่าบอน",},
		{ProvinceID: 36, District_name: "บางแก้ว",},
		{ProvinceID: 36, District_name: "ป่าพะยอม",},
		{ProvinceID: 36, District_name: "ศรีนครินทร์",},

		{ProvinceID: 37, District_name: "เมืองพิจิตร",},
		{ProvinceID: 37, District_name: "ทรายพูน",},
		{ProvinceID: 37, District_name: "โพธิ์ประทับช้าง",},
		{ProvinceID: 37, District_name: "ตะพานหิน",},
		{ProvinceID: 37, District_name: "บางมูลนาก",},
		{ProvinceID: 37, District_name: "โพทะเล",},
		{ProvinceID: 37, District_name: "สามง่าม",},
		{ProvinceID: 37, District_name: "ทับคล้อ",},
		{ProvinceID: 37, District_name: "สากเหล็ก",},
		{ProvinceID: 37, District_name: "บึงนาราง",},
		{ProvinceID: 37, District_name: "ดงเจริญ",},
		{ProvinceID: 37, District_name: "วชิรบารมี",},

		{ProvinceID: 38, District_name: "เมืองพิษณุโลก",},
		{ProvinceID: 38, District_name: "นครไทย",},
		{ProvinceID: 38, District_name: "ชาติตระการ",},
		{ProvinceID: 38, District_name: "บางระกำ",},
		{ProvinceID: 38, District_name: "บางกระทุ่ม",},
		{ProvinceID: 38, District_name: "พรหมพิราม",},
		{ProvinceID: 38, District_name: "วัดโบสถ์",},
		{ProvinceID: 38, District_name: "วังทอง",},
		{ProvinceID: 38, District_name: "เนินมะปราง",},
		
		{ProvinceID: 39, District_name: "เมืองเพชรบุรี",},
		{ProvinceID: 39, District_name: "เขาย้อย",},
		{ProvinceID: 39, District_name: "บ้านลาด",},
		{ProvinceID: 39, District_name: "บ้านแหลม",},
		{ProvinceID: 39, District_name: "ท่ายาง",},
		{ProvinceID: 39, District_name: "ชะอำ",},
		{ProvinceID: 39, District_name: "หนองหญ้าปล้อง",},
		{ProvinceID: 39, District_name: "แก่งกระจาน",},

		{ProvinceID: 40, District_name: "เมืองเพชรบูรณ์",},
		{ProvinceID: 40, District_name: "ชนแดน",},
		{ProvinceID: 40, District_name: "หล่มสัก",},
		{ProvinceID: 40, District_name: "หล่มเก่า",},
		{ProvinceID: 40, District_name: "วิเชียรบุรี",},
		{ProvinceID: 40, District_name: "ศรีเทพ",},
		{ProvinceID: 40, District_name: "หนองไผ่",},
		{ProvinceID: 40, District_name: "บึงสามพัน",},
		{ProvinceID: 40, District_name: "น้ำหนาว",},
		{ProvinceID: 40, District_name: "วังโป่ง",},
		{ProvinceID: 40, District_name: "เขาค้อ",},

		{ProvinceID: 41, District_name: "เมืองแพร่",},
		{ProvinceID: 41, District_name: "เด่นชัย",},
		{ProvinceID: 41, District_name: "ร้องกวาง",},
		{ProvinceID: 41, District_name: "ลอง",},
		{ProvinceID: 41, District_name: "วังชิ้น",},
		{ProvinceID: 41, District_name: "สอง",},
		{ProvinceID: 41, District_name: "สูงเม่น",},
		{ProvinceID: 41, District_name: "หนองม่วงไข่",},

		{ProvinceID: 42, District_name: "เมืองภูเก็ต",},
		{ProvinceID: 42, District_name: "ถลาง",},
		{ProvinceID: 42, District_name: "กะทู้",},

		{ProvinceID: 43, District_name: "เมืองมหาสารคาม",},
		{ProvinceID: 43, District_name: "แกดำ",},
		{ProvinceID: 43, District_name: "โกสุมพิสัย",},
		{ProvinceID: 43, District_name: "กันทรวิชัย",},
		{ProvinceID: 43, District_name: "เชียงยืน",},
		{ProvinceID: 43, District_name: "บรบือ",},
		{ProvinceID: 43, District_name: "นาเชือก",},
		{ProvinceID: 43, District_name: "พยัคฆภูมิพิสัย",},
		{ProvinceID: 43, District_name: "วาปีปทุม",},
		{ProvinceID: 43, District_name: "นาดูน",},
		{ProvinceID: 43, District_name: "ยางสีสุราช",},
		{ProvinceID: 43, District_name: "กุดรัง",},
		{ProvinceID: 43, District_name: "ชื่นชม",},

		{ProvinceID: 44, District_name: "เมืองมุกดาหาร",},
		{ProvinceID: 44, District_name: "นิคมคำสร้อย",},
		{ProvinceID: 44, District_name: "ดอนตาล",},
		{ProvinceID: 44, District_name: "ดงหลวง",},
		{ProvinceID: 44, District_name: "คำชะอี",},
		{ProvinceID: 44, District_name: "หว้านใหญ่",},
		{ProvinceID: 44, District_name: "หนองสูง",},
		
		{ProvinceID: 45, District_name: "เมืองแม่ฮ่องสอน",},
		{ProvinceID: 45, District_name: "ขุนยวม",},
		{ProvinceID: 45, District_name: "ปาย",},
		{ProvinceID: 45, District_name: "แม่สะเรียง",},
		{ProvinceID: 45, District_name: "แม่ลาน้อย",},
		{ProvinceID: 45, District_name: "สบเมย",},
		{ProvinceID: 45, District_name: "ปางมะผ้า",},

		{ProvinceID: 46, District_name: "เมืองยโสธร",},
		{ProvinceID: 46, District_name: "ทรายมูล",},
		{ProvinceID: 46, District_name: "กุดชุม",},
		{ProvinceID: 46, District_name: "คำเขื่อนแก้ว",},
		{ProvinceID: 46, District_name: "ป่าติ้ว",},
		{ProvinceID: 46, District_name: "มหาชนะชัย",},
		{ProvinceID: 46, District_name: "ค้อวัง",},
		{ProvinceID: 46, District_name: "เลิงนกทา",},
		{ProvinceID: 46, District_name: "ไทยเจริญ",},

		{ProvinceID: 47, District_name: "เมืองยะลา",},
		{ProvinceID: 47, District_name: "เบตง",},
		{ProvinceID: 47, District_name: "บันนังสตา",},
		{ProvinceID: 47, District_name: "ธารโต",},
		{ProvinceID: 47, District_name: "ยะหา",},
		{ProvinceID: 47, District_name: "รามัน",},
		{ProvinceID: 47, District_name: "กาบัง",},
		{ProvinceID: 47, District_name: "กรงปินัง",},

		{ProvinceID: 48, District_name: "เมืองร้อยเอ็ด",},
		{ProvinceID: 48, District_name: "เกษตรวิสัย",},
		{ProvinceID: 48, District_name: "ปทุมรัตต์",},
		{ProvinceID: 48, District_name: "จตุรพักตรพิมาน",},
		{ProvinceID: 48, District_name: "ธวัชบุรี",},
		{ProvinceID: 48, District_name: "พนมไพร",},
		{ProvinceID: 48, District_name: "โพนทอง",},
		{ProvinceID: 48, District_name: "โพธิ์ชัย",},
		{ProvinceID: 48, District_name: "หนองพอก",},
		{ProvinceID: 48, District_name: "เสลภูมิ",},
		{ProvinceID: 48, District_name: "สุวรรณภูมิ",},
		{ProvinceID: 48, District_name: "เมืองสรวง",},
		{ProvinceID: 48, District_name: "โพนทราย",},
		{ProvinceID: 48, District_name: "อาจสามารถ",},
		{ProvinceID: 48, District_name: "เมยวดี",},
		{ProvinceID: 48, District_name: "ศรีสมเด็จ",},
		{ProvinceID: 48, District_name: "จังหาร",},
		{ProvinceID: 48, District_name: "เชียงขวัญ",},
		{ProvinceID: 48, District_name: "หนองฮี",},
		{ProvinceID: 48, District_name: "ทุ่งเขาหลวง",},
		
		{ProvinceID: 49, District_name: "เมืองระนอง",},
		{ProvinceID: 49, District_name: "กะเปอร์",},
		{ProvinceID: 49, District_name: "กระบุรี",},
		{ProvinceID: 49, District_name: "ละอุ่น",},
		{ProvinceID: 49, District_name: "สุขสำราญ",},

		{ProvinceID: 50, District_name: "เมืองระยอง",},
		{ProvinceID: 50, District_name: "บ้านฉาง",},
		{ProvinceID: 50, District_name: "แกลง",},
		{ProvinceID: 50, District_name: "วังจันทร์",},
		{ProvinceID: 50, District_name: "บ้านค่าย",},
		{ProvinceID: 50, District_name: "ปลวกแดง",},
		{ProvinceID: 50, District_name: "เขาชะเมา",},
		{ProvinceID: 50, District_name: "นิคมพัฒนา",},
		
		{ProvinceID: 51, District_name: "เมืองราชบุรี",},
		{ProvinceID: 51, District_name: "จอมบึง",},
		{ProvinceID: 51, District_name: "สวนผึ้ง",},
		{ProvinceID: 51, District_name: "ดำเนินสะดวก",},
		{ProvinceID: 51, District_name: "บ้านโป่ง",},
		{ProvinceID: 51, District_name: "บางแพ",},
		{ProvinceID: 51, District_name: "โพธาราม",},
		{ProvinceID: 51, District_name: "ปากท่อ",},
		{ProvinceID: 51, District_name: "วัดเพลง",},
		{ProvinceID: 51, District_name: "บ้านคา",},

		{ProvinceID: 52, District_name: "เมืองลพบุรี",},
		{ProvinceID: 52, District_name: "พัฒนานิคม",},
		{ProvinceID: 52, District_name: "โคกสำโรง",},
		{ProvinceID: 52, District_name: "ชัยบาดาล",},
		{ProvinceID: 52, District_name: "ท่าวุ้ง",},
		{ProvinceID: 52, District_name: "บ้านหมี่",},
		{ProvinceID: 52, District_name: "ท่าหลวง",},
		{ProvinceID: 52, District_name: "สระโบสถ์",},
		{ProvinceID: 52, District_name: "โคกเจริญ",},
		{ProvinceID: 52, District_name: "ลำสนธิ",},
		{ProvinceID: 52, District_name: "หนองม่วง",},

		{ProvinceID: 53, District_name: "เมืองลำปาง",},	
		{ProvinceID: 53, District_name: "ห้างฉัตร",},
		{ProvinceID: 53, District_name: "เสริมงาม",},
		{ProvinceID: 53, District_name: "สบปราบ",},
		{ProvinceID: 53, District_name: "วังเหนือ",},
		{ProvinceID: 53, District_name: "แม่เมาะ",},
		{ProvinceID: 53, District_name: "แม่พริก",},
		{ProvinceID: 53, District_name: "แม่ทะ",},
		{ProvinceID: 53, District_name: "เมืองปาน",},
		{ProvinceID: 53, District_name: "เถิน",},
		{ProvinceID: 53, District_name: "แจ้ห่ม",},
		{ProvinceID: 53, District_name: "งาว",},
		{ProvinceID: 53, District_name: "เกาะคา",},

		{ProvinceID: 54, District_name: "เมืองลำพูน",},
		{ProvinceID: 54, District_name: "แม่ทา",},
		{ProvinceID: 54, District_name: "บ้านโฮ่ง",},
		{ProvinceID: 54, District_name: "ลี้",},
		{ProvinceID: 54, District_name: "ทุ่งหัวช้าง",},
		{ProvinceID: 54, District_name: "ป่าซาง",},
		{ProvinceID: 54, District_name: "บ้านธิ",},
		{ProvinceID: 54, District_name: "เวียงหนองล่อง",},

		{ProvinceID: 55, District_name: "เมืองเลย",},
		{ProvinceID: 55, District_name: "นาด้วง",},
		{ProvinceID: 55, District_name: "เชียงคาน",},
		{ProvinceID: 55, District_name: "ปากชม",},
		{ProvinceID: 55, District_name: "ด่านซ้าย",},
		{ProvinceID: 55, District_name: "นาแห้ว",},
		{ProvinceID: 55, District_name: "ภูเรือ",},
		{ProvinceID: 55, District_name: "ท่าลี่",},
		{ProvinceID: 55, District_name: "วังสะพุง",},
		{ProvinceID: 55, District_name: "ภูกระดึง",},
		{ProvinceID: 55, District_name: "ภูหลวง",},
		{ProvinceID: 55, District_name: "ผาขาว",},
		{ProvinceID: 55, District_name: "เอราวัณ",},
		{ProvinceID: 55, District_name: "หนองหิน",},

		{ProvinceID: 56, District_name: "เมืองศรีสะเกษ",},
		{ProvinceID: 56, District_name: "ชุมน้อย",},
		{ProvinceID: 56, District_name: "กันทรารมย์",},
		{ProvinceID: 56, District_name: "กันทรลักษ์",},
		{ProvinceID: 56, District_name: "ขุขันธ์",},
		{ProvinceID: 56, District_name: "ไพรบึง",},
		{ProvinceID: 56, District_name: "ปรางค์กู่",},
		{ProvinceID: 56, District_name: "ขุนหาญ",},
		{ProvinceID: 56, District_name: "ราษีไศล",},
		{ProvinceID: 56, District_name: "อุทุมพรพิสัย",},
		{ProvinceID: 56, District_name: "บึงบูรพ์",},
		{ProvinceID: 56, District_name: "ห้วยทับทัน",},
		{ProvinceID: 56, District_name: "โนนคูณ",},
		{ProvinceID: 56, District_name: "ศรีรัตนะ",},
		{ProvinceID: 56, District_name: "น้ำเกลี้ยง",},
		{ProvinceID: 56, District_name: "วังหิน",},
		{ProvinceID: 56, District_name: "ภูสิงห์",},
		{ProvinceID: 56, District_name: "เมืองจันทร์",},
		{ProvinceID: 56, District_name: "เบญจลักษ์",},
		{ProvinceID: 56, District_name: "พยุห์",},
		{ProvinceID: 56, District_name: "โพธิ์ศรีสุวรรณ",},
		{ProvinceID: 56, District_name: "ศิลาลาด",},

		{ProvinceID: 57, District_name: "เมืองสกลนคร",},
		{ProvinceID: 57, District_name: "กุสุมาลย์",},
		{ProvinceID: 57, District_name: "กุดบาก",},
		{ProvinceID: 57, District_name: "พรรณานิคม",},
		{ProvinceID: 57, District_name: "พังโคน",},
		{ProvinceID: 57, District_name: "วาริชภูมิ",},
		{ProvinceID: 57, District_name: "นิคมน้ำอูน",},
		{ProvinceID: 57, District_name: "วานรนิวาส",},
		{ProvinceID: 57, District_name: "คำตากล้า",},
		{ProvinceID: 57, District_name: "คำม่วง",},
		{ProvinceID: 57, District_name: "อากาศอำนวย",},
		{ProvinceID: 57, District_name: "สว่างแดนดิน",},
		{ProvinceID: 57, District_name: "ส่องดาว",},
		{ProvinceID: 57, District_name: "เต่างอย",},
		{ProvinceID: 57, District_name: "โคกศรีสุพรรณ",},
		{ProvinceID: 57, District_name: "เจริญศิลป์",},
		{ProvinceID: 57, District_name: "โพนนาแก้ว",},
		{ProvinceID: 57, District_name: "ภูพาน",},

		{ProvinceID: 58, District_name: "เมืองสงขลา",},
		{ProvinceID: 58, District_name: "กระแสสินธุ์",},
		{ProvinceID: 58, District_name: "คลองหอยโข่ง",},
		{ProvinceID: 58, District_name: "ควนเนียง",},
		{ProvinceID: 58, District_name: "จะนะ",},
		{ProvinceID: 58, District_name: "เทพา",},
		{ProvinceID: 58, District_name: "นาทวี",},
		{ProvinceID: 58, District_name: "นาหม่อม",},
		{ProvinceID: 58, District_name: "บางกล่ำ",},
		{ProvinceID: 58, District_name: "ระโนด",},
		{ProvinceID: 58, District_name: "รัตภูมิ",},
		{ProvinceID: 58, District_name: "สทิงพระ",},
		{ProvinceID: 58, District_name: "สะเดา",},
		{ProvinceID: 58, District_name: "สะบ้าย้อย",},
		{ProvinceID: 58, District_name: "สิงหนคร",},
		{ProvinceID: 58, District_name: "หาดใหญ่",},

		{ProvinceID: 59, District_name: "เมืองสตูล",},
		{ProvinceID: 59, District_name: "ควนโดน",},
		{ProvinceID: 59, District_name: "ควนกาหลง",},
		{ProvinceID: 59, District_name: "ท่าแพ",},
		{ProvinceID: 59, District_name: "ละงู",},
		{ProvinceID: 59, District_name: "ทุ่งหว้า",},
		{ProvinceID: 59, District_name: "มะนัง",},

		{ProvinceID: 60, District_name: "เมืองสมุทรปราการ",},
		{ProvinceID: 60, District_name: "บางบ่อ",},
		{ProvinceID: 60, District_name: "บางพลี",},
		{ProvinceID: 60, District_name: "พระประแดง",},
		{ProvinceID: 60, District_name: "พระสมุทรเจดีย์",},
		{ProvinceID: 60, District_name: "บางเสาธง",},

		{ProvinceID: 61, District_name: "เมืองสมุทรสงคราม",},
		{ProvinceID: 61, District_name: "บางคนที",},
		{ProvinceID: 61, District_name: "อัมพวา",},
		
		{ProvinceID: 62, District_name: "เมืองสมุทรสาคร",},
		{ProvinceID: 62, District_name: "บ้านแพ้ว",},
		{ProvinceID: 62, District_name: "กระทุ่มแบน",},

		{ProvinceID: 63, District_name: "เมืองสระแก้ว",},
		{ProvinceID: 63, District_name: "คลองหาด",},
		{ProvinceID: 63, District_name: "ตาพระยา",},
		{ProvinceID: 63, District_name: "วังน้ำเย็น",},
		{ProvinceID: 63, District_name: "วัฒนานคร",},
		{ProvinceID: 63, District_name: "อรัญประเทศ",},
		{ProvinceID: 63, District_name: "เขาฉกรรจ์",},
		{ProvinceID: 63, District_name: "โคกสูง",},
		{ProvinceID: 63, District_name: "วังสมบูรณ์",},

		{ProvinceID: 64, District_name: "เมืองสระบุรี",},
		{ProvinceID: 64, District_name: "แก่งคอย",},
		{ProvinceID: 64, District_name: "หนองแค",},
		{ProvinceID: 64, District_name: "วิหารแดง",},
		{ProvinceID: 64, District_name: "หนองแซง",},
		{ProvinceID: 64, District_name: "บ้านหมอ",},
		{ProvinceID: 64, District_name: "ดอนพุด",},
		{ProvinceID: 64, District_name: "หนองโดน",},
		{ProvinceID: 64, District_name: "พระพุทธบาท",},
		{ProvinceID: 64, District_name: "เสาไห้",},
		{ProvinceID: 64, District_name: "มวกเหล็ก",},
		{ProvinceID: 64, District_name: "วังม่วง",},
		{ProvinceID: 64, District_name: "เฉลิมพระเกียรติ",},

		{ProvinceID: 65, District_name: "เมืองสิงห์บุรี",},
		{ProvinceID: 65, District_name: "ค่ายบางระจัน",},
		{ProvinceID: 65, District_name: "ท่าช้าง",},
		{ProvinceID: 65, District_name: "บางระจัน",},
		{ProvinceID: 65, District_name: "พรหมบุรี",},
		{ProvinceID: 65, District_name: "อินทร์บุรี",},

		{ProvinceID: 66, District_name: "เมืองสุโขทัย",},
		{ProvinceID: 66, District_name: "สวรรคโลก",},
		{ProvinceID: 66, District_name: "ศรีสำโรง",},
		{ProvinceID: 66, District_name: "ศรีสัชนาลัย",},
		{ProvinceID: 66, District_name: "ศรีนคร",},
		{ProvinceID: 66, District_name: "บ้านด่านลานหอย",},
		{ProvinceID: 66, District_name: "ทุ่งเสลี่ยม",},
		{ProvinceID: 66, District_name: "คีรีมาศ",},
		{ProvinceID: 66, District_name: "กงไกรลาศ",},
		
		{ProvinceID: 67, District_name: "เมืองสุพรรณบุรี",},
		{ProvinceID: 67, District_name: "เดิมบางนางบวช",},
		{ProvinceID: 67, District_name: "ด่านช้าง",},
		{ProvinceID: 67, District_name: "บางปลาม้า",},
		{ProvinceID: 67, District_name: "ศรีประจันต์",},
		{ProvinceID: 67, District_name: "ดอนเจดีย์",},
		{ProvinceID: 67, District_name: "สองพี่น้อง",},
		{ProvinceID: 67, District_name: "สามชุก",},
		{ProvinceID: 67, District_name: "อู่ทอง",},
		{ProvinceID: 67, District_name: "หนองหญ้าไซ",},

		{ProvinceID: 68, District_name: "เมืองสุราษฎร์ธานี",},
		{ProvinceID: 68, District_name: "กาญจนดิษฐ์",},
		{ProvinceID: 68, District_name: "ดอนสัก",},
		{ProvinceID: 68, District_name: "เกาะสมุย",},
		{ProvinceID: 68, District_name: "เกาะพะงัน",},
		{ProvinceID: 68, District_name: "ไชยา",},
		{ProvinceID: 68, District_name: "ท่าชนะ",},
		{ProvinceID: 68, District_name: "คีรีรัฐนิคม",},
		{ProvinceID: 68, District_name: "บ้านตาขุน",},
		{ProvinceID: 68, District_name: "พนม",},
		{ProvinceID: 68, District_name: "ท่าฉาง",},
		{ProvinceID: 68, District_name: "บ้านนาสาร",},
		{ProvinceID: 68, District_name: "บ้านนาเดิม",},
		{ProvinceID: 68, District_name: "เคียนซา",},
		{ProvinceID: 68, District_name: "เวียงสระ",},
		{ProvinceID: 68, District_name: "พระแสง",},
		{ProvinceID: 68, District_name: "พุนพิน",},
		{ProvinceID: 68, District_name: "ชัยบุรี",},
		{ProvinceID: 68, District_name: "วิภาวดี",},

		{ProvinceID: 69, District_name: "สุรินทร์",},
		{ProvinceID: 69, District_name: "สำโรงทาบ",},
		{ProvinceID: 69, District_name: "สังขะ",},
		{ProvinceID: 69, District_name: "สนม",},
		{ProvinceID: 69, District_name: "ศีขรภูมิ",},
		{ProvinceID: 69, District_name: "ศรีณรงค์",},
		{ProvinceID: 69, District_name: "รัตนบุรี",},
		{ProvinceID: 69, District_name: "พนมดงรัก",},
		{ProvinceID: 69, District_name: "ปราสาท",},
		{ProvinceID: 69, District_name: "บัวเชด",},
		{ProvinceID: 69, District_name: "โนนนารายณ์",},
		{ProvinceID: 69, District_name: "ท่าตูม",},
		{ProvinceID: 69, District_name: "ชุมพลบุรี",},
		{ProvinceID: 69, District_name: "จอมพระ",},
		{ProvinceID: 69, District_name: "เขวาสินรินทร์",},
		{ProvinceID: 69, District_name: "กาบเชิง",},

		{ProvinceID: 70, District_name: "เมืองหนองคาย",},
		{ProvinceID: 70, District_name: "ท่าบ่อ",},
		{ProvinceID: 70, District_name: "เฝ้าไร่",},
		{ProvinceID: 70, District_name: "โพธิ์ตาก",},
		{ProvinceID: 70, District_name: "โพนพิสัย",},
		{ProvinceID: 70, District_name: "รัตนวาปี",},
		{ProvinceID: 70, District_name: "ศรีเชียงใหม่",},
		{ProvinceID: 70, District_name: "สระใคร",},
		{ProvinceID: 70, District_name: "สังคม",},
		
		{ProvinceID: 71, District_name: "เมืองหนองบัวลำภู",},
		{ProvinceID: 71, District_name: "นากลาง",},
		{ProvinceID: 71, District_name: "โนนสัง",},
		{ProvinceID: 71, District_name: "ศรีบุญเรือง",},
		{ProvinceID: 71, District_name: "สุวรรณคูหา",},
		{ProvinceID: 71, District_name: "ศรีบุญเรือง",},
		{ProvinceID: 71, District_name: "นาวัง",},

		{ProvinceID: 72, District_name: "เมืองอ่างทอง",},
		{ProvinceID: 72, District_name: "ไชโย",},
		{ProvinceID: 72, District_name: "ป่าโมก",},
		{ProvinceID: 72, District_name: "โพธิ์ทอง",},
		{ProvinceID: 72, District_name: "แสวงหา",},
		{ProvinceID: 72, District_name: "วิเศษชัยชาญ",},
		{ProvinceID: 72, District_name: "สามโก้",},	
		
		{ProvinceID: 73, District_name: "เมืองอำนาจเจริญ",},
		{ProvinceID: 73, District_name: "ชานุมาน",},
		{ProvinceID: 73, District_name: "ปทุมราชวงศา",},
		{ProvinceID: 73, District_name: "พนา",},
		{ProvinceID: 73, District_name: "เสนางคนิคม",},
		{ProvinceID: 73, District_name: "หัวตะพาน",},
		{ProvinceID: 73, District_name: "ลืออำนาจ",},
		
		{ProvinceID: 74, District_name: "เมืองอุดรธานี",},
		{ProvinceID: 74, District_name: "กุมจับ",},
		{ProvinceID: 74, District_name: "หนองวัวซอ" ,},
		{ProvinceID: 74, District_name: "กุมภวาปี",},
		{ProvinceID: 74, District_name: "โนนสะอาด",},
		{ProvinceID: 74, District_name: "หนองหาน",},
		{ProvinceID: 74, District_name: "ทุ่งฝน",},
		{ProvinceID: 74, District_name: "ไชยวาน",},
		{ProvinceID: 74, District_name: "ศรีธาตุ",},
		{ProvinceID: 74, District_name: "วังสามหมอ",},
		{ProvinceID: 74, District_name: "บ้านดุง",},
		{ProvinceID: 74, District_name: "บ้านผือ",},
		{ProvinceID: 74, District_name: "น้ำโสม",},
		{ProvinceID: 74, District_name: "เพ็ญ",},
		{ProvinceID: 74, District_name: "สร้างคอม",},
		{ProvinceID: 74, District_name: "หนองแสง",},
		{ProvinceID: 74, District_name: "นายูง",},
		{ProvinceID: 74, District_name: "พิบูลย์รักษ์",},
		{ProvinceID: 74, District_name: "กู่แก้ว",},
		{ProvinceID: 74, District_name: "ประจักษ์ศิลปาคม",},

		{ProvinceID: 75, District_name: "เมืองอุตรดิตถ์",},
		{ProvinceID: 75, District_name: "ตรอน",},
		{ProvinceID: 75, District_name: "ท่าปลา",},
		{ProvinceID: 75, District_name: "น้ำปาด",},
		{ProvinceID: 75, District_name: "ฟากท่า",},
		{ProvinceID: 75, District_name: "บ้านโคก",},
		{ProvinceID: 75, District_name: "พิชัย",},
		{ProvinceID: 75, District_name: "ลับแล",},
		{ProvinceID: 75, District_name: "ทองแสนขัน",},

		{ProvinceID: 76, District_name: "เมืองอุทัยธานี",},
		{ProvinceID: 76, District_name: "บ้านไร่",},
		{ProvinceID: 76, District_name: "ห้วยคต",},
		{ProvinceID: 76, District_name: "หนวงฉาง",},
		{ProvinceID: 76, District_name: "หนวงขาหย่าง",},
		{ProvinceID: 76, District_name: "สว่างอารมณ์",},
		{ProvinceID: 76, District_name: "ลานสัก",},
		{ProvinceID: 76, District_name: "ทัพทัน",},

		{ProvinceID: 77, District_name: "เมืองอุบลราชธานี",},
		{ProvinceID: 77, District_name: "ศรีเมืองใหม่",},
		{ProvinceID: 77, District_name: "โขงเจียม",},
		{ProvinceID: 77, District_name: "เขื่องใน",},
		{ProvinceID: 77, District_name: "เขมราฐ,"},
		{ProvinceID: 77, District_name: "เดชอุดม",},
		{ProvinceID: 77, District_name: "นาจะหลวย",},
		{ProvinceID: 77, District_name: "น้ำยืน",},
		{ProvinceID: 77, District_name: "บุญฑริก",},
		{ProvinceID: 77, District_name: "ตระการพืชผล",},
		{ProvinceID: 77, District_name: "กุดข้าวปุ้น",},
		{ProvinceID: 77, District_name: "ม่วงสามสิบ",},
		{ProvinceID: 77, District_name: "วารินชำราบ",},
		{ProvinceID: 77, District_name: "พิบูลมังสาหาร",},
		{ProvinceID: 77, District_name: "ตาลสุม",},
		{ProvinceID: 77, District_name: "โพธิ์ไทร",},
		{ProvinceID: 77, District_name: "สำโรง",},
		{ProvinceID: 77, District_name: "เดอนมดแดง",},
		{ProvinceID: 77, District_name: "สิรินธร",},
		{ProvinceID: 77, District_name: "ทุ่งศรีอุดม",},
		{ProvinceID: 77, District_name: "นาเยีย",},
		{ProvinceID: 77, District_name: "นาตาล",},
		{ProvinceID: 77, District_name: "เหล่าเสือโก้ก",},
		{ProvinceID: 77, District_name: "สว่างวีระพงค์",},
		{ProvinceID: 77, District_name: "น้ำขุ่น",},
		



		
		
		

		

		
		
		
		





		
	})
}