package config
import (
	"github.com/lnwzaaa007/Project_SA_School-system/backend/entity"
	
)
func seedTeachers(){
	db.Model(&entity.Teacher{}).Create([]entity.Teacher{
		{
			Teacher_ID:   "T20001",
			TitleID:     1,
			TFirst_Name:  "สมศรี",
			TLast_Name:   "ผ่องใจ",
			EFirst_Name:  "Somsri",
			ELast_Name:   "pongjia",
			Citizen_ID:   "1101700234567",
			Tel:          "0812345678",
			DateOfBirth:  mustDate("1986-03-20"),
			Gender:       entity.Gendertype("Female"),
			Nationality:  "Thai",
			Email:        "Somsri.T540001@example.com",
			Religious:    "Buddhist",
			Teacher_image: nil,
			Qualification: "สาขาคณิตศาสตร์",
			Qualification_image: nil,
			AddressID:    1,
			UsersID: 3,	
		},
		{
		Teacher_ID:   "T20002",
		TitleID:      1,
		TFirst_Name:  "ประทีป",
		TLast_Name:   "ใจดี",
		EFirst_Name:  "Prateep",
		ELast_Name:   "Jaidee",
		Citizen_ID:   "1101700234568",
		Tel:          "0823456789",
		DateOfBirth:  mustDate("1982-07-15"),
		Gender:       entity.Gendertype("Male"),
		Nationality:  "Thai",
		Email:        "prateep.t540002@example.com",
		Religious:    "Buddhist",
		Teacher_image: nil,
		Qualification: "สาขาวิทยาศาสตร์",
		Qualification_image: nil,
		AddressID:    2,
		UsersID:      5,
	},
	{
		Teacher_ID:   "T20003",
		TitleID:      2,
		TFirst_Name:  "ณัฐวุฒิ",
		TLast_Name:   "รักเรียน",
		EFirst_Name:  "Nattawut",
		ELast_Name:   "Rukrean",
		Citizen_ID:   "1101700234569",
		Tel:          "0834567890",
		DateOfBirth:  mustDate("1990-01-10"),
		Gender:       entity.Gendertype("Male"),
		Nationality:  "Thai",
		Email:        "nattawut.t540003@example.com",
		Religious:    "Buddhist",
		Teacher_image: nil,
		Qualification: "สาขาภาษาไทย",
		Qualification_image: nil,
		AddressID:    3,
		UsersID:      6,
	},
	{
		Teacher_ID:   "T20004",
		TitleID:      1,
		TFirst_Name:  "สุวรรณา",
		TLast_Name:   "ทองแท้",
		EFirst_Name:  "Suwanna",
		ELast_Name:   "Thongtae",
		Citizen_ID:   "1101700234570",
		Tel:          "0845678901",
		DateOfBirth:  mustDate("1985-11-05"),
		Gender:       entity.Gendertype("Female"),
		Nationality:  "Thai",
		Email:        "suwanna.t540004@example.com",
		Religious:    "Buddhist",
		Teacher_image: nil,
		Qualification: "สาขาภาษาอังกฤษ",
		Qualification_image: nil,
		AddressID:    4,
		UsersID:      7,
	},
	{
		Teacher_ID:   "T20005",
		TitleID:      3,
		TFirst_Name:  "กิตติศักดิ์",
		TLast_Name:   "สอนดี",
		EFirst_Name:  "Kittisak",
		ELast_Name:   "Sondee",
		Citizen_ID:   "1101700234571",
		Tel:          "0856789012",
		DateOfBirth:  mustDate("1980-09-12"),
		Gender:       entity.Gendertype("Male"),
		Nationality:  "Thai",
		Email:        "kittisak.t540005@example.com",
		Religious:    "Buddhist",
		Teacher_image: nil,
		Qualification: "สาขาฟิสิกส์",
		Qualification_image: nil,
		AddressID:    5,
		UsersID:      8,
	},
	})
}